site_url: https://hou-gallery.pages.dev

backend:
  name: github
  repo: houekaki-alt/hou-gallery
  branch: main
  base_url: https://decap-cms-oauth.hou-ekaki.workers.dev
  auth_endpoint: auth
  use_local_storage: true  


media_folder: "images"
public_folder: "/images"

collections:
  - name: "site"
    label: "サイトデータ"
    files:
      - file: "images.json"
        label: "images.json"
        name: "images_json"
        fields:
          - label: "中身"
            name: "data"
            widget: "text"


